
import __ASTRO_IMAGE_IMPORT_5H3cT from "@assets/promos/flora-promo/promo-1.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fflora.md";
import __ASTRO_IMAGE_IMPORT_1vVI8c from "@assets/promos/flora-promo/promo-2.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fflora.md";
import __ASTRO_IMAGE_IMPORT_Z280JKr from "@assets/promos/flora-promo/promo-3.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fflora.md";
import __ASTRO_IMAGE_IMPORT_ZGL4P9 from "@assets/promos/flora-promo/promo-4.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fflora.md";
import __ASTRO_IMAGE_IMPORT_Z2klghM from "@assets/promos/photo-gallery-promo/promo-1.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fphoto-gallery.md";
import __ASTRO_IMAGE_IMPORT_Z2ln2VI from "@assets/promos/photo-gallery-promo/promo-2.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fphoto-gallery.md";
import __ASTRO_IMAGE_IMPORT_Z2moOAE from "@assets/promos/photo-gallery-promo/promo-3.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fphoto-gallery.md";
import __ASTRO_IMAGE_IMPORT_14nw4C from "@assets/promos/ruckas-muiza-promo/promo-1.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fruckas-muiza.md";
import __ASTRO_IMAGE_IMPORT_Z4GeJk from "@assets/promos/ruckas-muiza-promo/promo-2.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fruckas-muiza.md";
import __ASTRO_IMAGE_IMPORT_Z1dL0yh from "@assets/promos/ruckas-muiza-promo/promo-3.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fruckas-muiza.md";
import __ASTRO_IMAGE_IMPORT_Z2mPLne from "@assets/promos/ruckas-muiza-promo/promo-4.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fruckas-muiza.md";
export default new Map([["@assets/promos/flora-promo/promo-1.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fflora.md", __ASTRO_IMAGE_IMPORT_5H3cT], ["@assets/promos/flora-promo/promo-2.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fflora.md", __ASTRO_IMAGE_IMPORT_1vVI8c], ["@assets/promos/flora-promo/promo-3.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fflora.md", __ASTRO_IMAGE_IMPORT_Z280JKr], ["@assets/promos/flora-promo/promo-4.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fflora.md", __ASTRO_IMAGE_IMPORT_ZGL4P9], ["@assets/promos/photo-gallery-promo/promo-1.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fphoto-gallery.md", __ASTRO_IMAGE_IMPORT_Z2klghM], ["@assets/promos/photo-gallery-promo/promo-2.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fphoto-gallery.md", __ASTRO_IMAGE_IMPORT_Z2ln2VI], ["@assets/promos/photo-gallery-promo/promo-3.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fphoto-gallery.md", __ASTRO_IMAGE_IMPORT_Z2moOAE], ["@assets/promos/ruckas-muiza-promo/promo-1.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fruckas-muiza.md", __ASTRO_IMAGE_IMPORT_14nw4C], ["@assets/promos/ruckas-muiza-promo/promo-2.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fruckas-muiza.md", __ASTRO_IMAGE_IMPORT_Z4GeJk], ["@assets/promos/ruckas-muiza-promo/promo-3.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fruckas-muiza.md", __ASTRO_IMAGE_IMPORT_Z1dL0yh], ["@assets/promos/ruckas-muiza-promo/promo-4.webp?astroContentImageFlag=&importer=src%2Fassets%2Fmarkdown%2Fprojects%2Fruckas-muiza.md", __ASTRO_IMAGE_IMPORT_Z2mPLne]]);
		